# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Build and Test

# With this configuration, the workflow will run on every push.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build:
    name: Bazel Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            .cache
            tools/.bin
          key: ${{ runner.os }}-build

      - name: Build
        run: ./bazel --bazelrc=ci/.bazelrc build ...

      - name: Test
        run: ./bazel --bazelrc=ci/.bazelrc test ...
